# # twitter tweet doc: https://dev.twitter.com/docs/platform-objects/tweets

status0 = {
    "char_count_bucket": "0-19",
    "contributors": None,
    "scopes": None,
    "text": "This is a tweet",
    "hashtags": None,
    "in_reply_to_status_id": None,
    "user_friends_count": None,
    "favorite_count": 500,
    "source": "<a href=\"http://www.socialflow.com\" rel=\"nofollow\">SocialFlow</a>",
    "coordinates": None,
    "entities": "{\"user_mentions\": [], \"hashtags\": [], \"urls\": []}",
    "user_pit_statuses_count": None,
    "in_reply_to_screen_name": None,
    "in_reply_to_user_id": None,
    "retweet_count": 500,
    "user_name": "test",
    "orig_src": None,
    "hash_tags": None,
    "user_followers_count": None,
    "retweeted_status": None,
    "status_id": 286154818974646272,
    "trackable_links": None,
    "user_mentions": None,
    "geo": None,
    "classifiers": None,
    "lang": "en",
    "created_at": "2014-01-01T00:00:00",
    "place": None,
    "urls": None
}
status1 = {
    "char_count_bucket": "20-39",
    "contributors": None,
    "scopes": None,
    "text": "This is another tweet",
    "hashtags": None,
    "in_reply_to_status_id": None,
    "user_friends_count": None,
    "favorite_count": 600,
    "source": "<a href=\"http://www.socialflow.com\" rel=\"nofollow\">SocialFlow</a>",
    "coordinates": None,
    "entities": "{\"user_mentions\": [], \"hashtags\": [], \"urls\": []}",
    "user_pit_statuses_count": None,
    "in_reply_to_screen_name": None,
    "in_reply_to_user_id": None,
    "retweet_count": 600,
    "user_name": "test",
    "orig_src": None,
    "hash_tags": None,
    "user_followers_count": None,
    "retweeted_status": None,
    "status_id": 286169918469046272,
    "trackable_links": None,
    "user_mentions": None,
    "geo": None,
    "classifiers": None,
    "lang": "en",
    "created_at": "2014-01-02T00:00:00",
    "place": None,
    "urls": None
}
status2 = {
    "char_count_bucket": "40-59",
    "contributors": None,
    "scopes": None,
    "text": "@foouser This is an at reply to user tweet",
    "hashtags": None,
    "in_reply_to_status_id": None,
    "user_friends_count": None,
    "favorite_count": 600,
    "source": "<a href=\"http://www.socialflow.com\" rel=\"nofollow\">SocialFlow</a>",
    "coordinates": None,
    "entities": "{\"user_mentions\": [], \"hashtags\": [], \"urls\": []}",
    "user_pit_statuses_count": None,
    "in_reply_to_screen_name": "foouser",
    "in_reply_to_user_id": 1234567890,
    "retweet_count": 700,
    "user_name": "test",
    "orig_src": None,
    "hash_tags": None,
    "user_followers_count": None,
    "retweeted_status": None,
    "status_id": 286200117457846272,
    "trackable_links": None,
    "user_mentions": None,
    "geo": None,
    "classifiers": None,
    "lang": "en",
    "created_at": "2014-01-02T00:00:00",
    "place": None,
    "urls": None
}